services:
  # app:
  #   bild: .
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped
  #   depends_on: 
  #     - postgres
  #     - minio

  minio:
    container_name: musikmarching-minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ".env"
    environment:
      MINIO_ROOT_USER: musikmarching
      MINIO_ROOT_PASSWORD: jembut
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    # environment:
    #   POSTGRES_USER: musikmarching
    #   POSTGRES_PASSWORD: jembut
    #   POSTGRES_DB: musikmarching-dev
    volumes:
      - /var/lib/postgresql/data
    restart: unless-stopped
