services:
  minio:
    container_name: musikmarching-minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ".env"
    volumes:
      - ~/minio/data:/data
    command: server /data
    restart: unless-stopped
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    restart: unless-stopped
