version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - postgres

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: musikmarching-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # pgadmin:
  #   container_name: container-pgadmin
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   restart: unless-stopped

volumes:
  postgres-data:
