// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getProfileByAccountId = `-- name: GetProfileByAccountId :one
select id, account_id
from profile p
where p.account_id = $1
limit 1
`

func (q *Queries) GetProfileByAccountId(ctx context.Context, accountID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByAccountId, accountID)
	var i Profile
	err := row.Scan(&i.ID, &i.AccountID)
	return i, err
}
