// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getProfileById = `-- name: GetProfileById :one
select id, name, created_at, updated_at, deleted_at
from profile p
where p.id = $1
limit 1
`

func (q *Queries) GetProfileById(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileById, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
