// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error)
	CreateContributor(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CreateScore(ctx context.Context, arg CreateScoreParams) error
	GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error)
	GetAccountById(ctx context.Context, id uuid.UUID) (GetAccountByIdRow, error)
	GetAccounts(ctx context.Context) ([]GetAccountsRow, error)
	GetContributorById(ctx context.Context, id uuid.UUID) (GetContributorByIdRow, error)
	GetProfileById(ctx context.Context, id uuid.UUID) (Profile, error)
	GetScoresByContributorId(ctx context.Context, id uuid.UUID) ([]Score, error)
	GetUnverifiedContributors(ctx context.Context) ([]Contributor, error)
	GetVerifiedScores(ctx context.Context) ([]GetVerifiedScoresRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (uuid.UUID, error)
	UpdateAccountRole(ctx context.Context, arg UpdateAccountRoleParams) (uuid.UUID, error)
	VerifyContributor(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
