// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: score.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createScore = `-- name: CreateScore :exec
WITH score_insert AS (
  INSERT INTO Score (title)
  VALUES ($2)
  RETURNING id
)
INSERT INTO profile_score_uploads (profile_id, score_id)
values($1, (SELECT id FROM score_insert))
`

type CreateScoreParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Title string    `db:"title" json:"title"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) error {
	_, err := q.db.Exec(ctx, createScore, arg.ID, arg.Title)
	return err
}

const getScoresByProfile = `-- name: GetScoresByProfile :many
select s.id, s.title, s.created_at, s.updated_at, s.deleted_at
from profile p
inner join profile_score_uploads psu on p.id = psu.profile_id
inner join score s on psu.score_id = s.id
where p.account_id = $1
group by s.id, s.title
`

func (q *Queries) GetScoresByProfile(ctx context.Context, accountID uuid.UUID) ([]Score, error) {
	rows, err := q.db.Query(ctx, getScoresByProfile, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Score{}
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
